# Generated by Django 5.0.7 on 2024-07-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
